spring:
  data:
    mongodb:
      uri: mongodb+srv://soumayaayadi40_db_user:ZIw6wHvU0T9vEXEU@cluster0.zxgdozh.mongodb.net/MorphoSE?retryWrites=true&w=majority&ssl=true&tls=true&tlsInsecure=true&tlsAllowInvalidCertificates=true&tlsAllowInvalidHostnames=true&tlsDisabledProtocols=TLSv1.2&connectTimeoutMS=5000&socketTimeoutMS=5000&serverSelectionTimeoutMS=5000
      database: MorphoSE
      auto-index-creation: true

server:
  port: 8080

logging:
  level:
    com.morphologie: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: DEBUG